### PR TITLE
Add homebrew formula

### PR DESCRIPTION
**Pull request by e1senh0rn**
Addressing #1 .
Formula can be submitted later to homebrew core (https://github.com/Homebrew/homebrew-core).

### CODE REVIEW

**Comment by seletskiy** [comment]
@e1senh0rn: Great stuff. One question: is it mandatory put `tubekit.rb` into `HomebrewFormula` directory? Can't we just put it in root dir?

**Comment by e1senh0rn** [comment]
@seletskiy Updated. Somehow I missed that homebrew also looks for formula in the root of the repo.

**Comment by e1senh0rn** [comment]
Absolutely! Will check it out. Could you meanwhile cut release with flags support?

**Comment by kovetskiy** [comment]
Sure, released it https://github.com/reconquest/tubekit/releases

**Comment by e1senh0rn** [comment]
Should be good now!

**Comment by kovetskiy** [comment]
That's awesome, thanks! Merged.

**Pull request merged**
